### ISSUE TITLE
copy method implementation in AgentMessage

### ISSUE THREAD

**Issue by lbattu** [root-11/maslite#16]
https://github.com/root-11/maslite/blob/83e82fe544e356f3d344ef9a78eb5c830e860238/maslite/__init__.py#L91-L95

Can we change the copy method in AgentMessage to 

`return copy.deepcopy(self)`?

It will reduce the need to write the same code in the created subclasses of the AgentMessage

**Comment by root-11** [comment]
I think the idea has merit. Why suffer from typing fatigue?

Let's try some implementations and make some measurements:

```python
import copy

class BaseMessage(object):
    def __init__(self, sender, receiver, topic):
        self.sender = sender
        self.receiver = receiver
        self.topic = topic
    
    def copy(self):
        return copy.deepcopy(self)

    def old_school_copy(self):
        return type(self)(**{k:v for k,v in self.__dict__.items() if not k.startswith("_")})

    def classic_copy(self):
        return BaseMessage(self.sender,self.receiver,self.topic)

class NewMessage(BaseMessage):
    def __init__(self, sender, receiver, topic, payload):
        super().__init__(sender,receiver,topic)
        self.payload = payload   
    
    def classic_copy(self):
        return NewMessage(self.sender,self.receiver,self.topic, self.payload)
```

The minimal baseline for our test:
```python
m1 = BaseMessage(1,2,3)
m2 = NewMessage(1,2,3,"payload")
```

The test results:
```python
%timeit m1.copy()
```
> 4.69 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

```python
%timeit m2.copy()
```
> 5.15 µs ± 47.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

```python
%timeit m1.old_school_copy()
```
> 874 ns ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

```python
%timeit m2.old_school_copy()
```
> 1.21 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

```python
%timeit m2.classic_copy()
```
> 274 ns ± 4.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

```python
%timeit m2.classic_copy()
```
> 468 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Now let's summarize:

|message| `copy`|`old_school_copy`| `classic_copy`|
|---|---|---|---|
| m1 | 4.69µs | 0.874µs | 0.274µs |
| m2 | 5.15µs | 1.21µs | 0.468µs |

Observations:
- deepcopy does some extra work, to assure decoupling at depth, but is 17x slower that "classic" and 5x slower than `old_school`.
- old school copy doesn't provide a guarantee that the subclass doesn't have a variable that startswith "_".
- `classic` is the fastest method, but requires the developer to be explicit.


Would you accept a 17x slowdown of the most used kernel operation?

**Comment by lbattu** [comment]
Thank you for conducting these performance tests and providing the results.  While the idea of reducing code repetition in subclasses is appealing, this performance impact might not be acceptable, especially for time-critical applications.
